# Generated by Django 5.2.4 on 2025-08-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
