# Generated by Django 5.2.4 on 2025-08-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_birth_date_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='1900-01-01', max_length=254),
            preserve_default=False,
        ),
    ]
